### ISSUE TITLE
remove authorization header on redirect to different host

### ISSUE THREAD

**Issue by zkat** [npm/node-fetch-npm#1]
`request` removes the authorization header while redirecting if the host changes: https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/lib/redirect.js#L134-L138

node-fetch is still sending all the headers, which is causing https://github.com/zkat/pacote/issues/87

So, we should remove that header too :)

**Comment by zkat** [comment]
I believe this is the code in node-fetch-npm for this: https://github.com/npm/node-fetch-npm/blob/latest/src/index.js#L91-L96

**Comment by ricardohbin** [comment]
@zkat the fix is very simple, but to test it will have some changes in `server.js` and `test.js`

**Comment by zkat** [comment]
This has been picked up over at #2 :D 🎉
