### ISSUE TITLE
Underlying dependencies using WTFPL licensed components

### ISSUE THREAD

**Issue by nkothari-zz** [npm/node-fetch-npm#4]
WTFPL is not a legally recognized license type and therefore has implications on how the code can be used in other projects.

node-fetch-npm [depends](https://github.com/npm/node-fetch-npm/blob/latest/package.json) on json-parse-helpfulerror which [depends](https://github.com/smikes/json-parse-helpfulerror/blob/master/package.json) on [jju](https://github.com/rlidwka/jju/blob/master/LICENSE) . Turns out there's already and [open issue and PR](https://github.com/rlidwka/jju/pull/24) requesting this but both jju and json-parse-helpfulerror seem to not be maintained.

Are there viable alternative components that can be utilized for the JSON parse error reporting so that npm isn't affected by the legal issues behind WTFPL?

**Comment by zkat** [comment]
Are you interested in submitting a PR to this repo that replaces `jju` with `parse-json`? If so, I'll take it.

**Comment by iarna** [comment]
`parse-json` inlines `jju` and [thus still has WTFPL licensed code](https://github.com/sindresorhus/parse-json/blob/master/vendor/parse.js#L4)
